const dataAll = {
    "caseOccurredYearDto": {
        "CaseAddNotClosedNumber": 159,
        "CaseAddClosedNumber": 31,
        "CaseAddNumber": 190
    },
    "caseOccurredWeekDto": {
        "CaseAddNotClosedNumber": 15,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 15
    },
    "highIncidenceCaseAnalysisMap": {
        "黑客": [{
            "caseNumber": "2",
            "caseTime": 1
        }, {
            "caseNumber": "0",
            "caseTime": 2
        }, {
            "caseNumber": "0",
            "caseTime": 3
        }, {
            "caseNumber": "1",
            "caseTime": 4
        }, {
            "caseNumber": "0",
            "caseTime": 5
        }, {
            "caseNumber": "10",
            "caseTime": 6
        }, {
            "caseNumber": "1",
            "caseTime": 7
        }, {
            "caseNumber": "3",
            "caseTime": 8
        }, {
            "caseNumber": "32",
            "caseTime": 9
        }, {
            "caseNumber": "1",
            "caseTime": 10
        }, {
            "caseNumber": "1",
            "caseTime": 11
        }, {
            "caseNumber": "9",
            "caseTime": 12
        }],
        "盗墓": [{
            "caseNumber": "1",
            "caseTime": 1
        }, {
            "caseNumber": "0",
            "caseTime": 2
        }, {
            "caseNumber": "6",
            "caseTime": 3
        }, {
            "caseNumber": "2",
            "caseTime": 4
        }, {
            "caseNumber": "0",
            "caseTime": 5
        }, {
            "caseNumber": "6",
            "caseTime": 6
        }, {
            "caseNumber": "4",
            "caseTime": 7
        }, {
            "caseNumber": "19",
            "caseTime": 8
        }, {
            "caseNumber": "1",
            "caseTime": 9
        }, {
            "caseNumber": "3",
            "caseTime": 10
        }, {
            "caseNumber": "0",
            "caseTime": 11
        }, {
            "caseNumber": "5",
            "caseTime": 12
        }]
    },
    "caseOccurredMonthDto": {
        "CaseAddNotClosedNumber": 41,
        "CaseAddClosedNumber": 5,
        "CaseAddNumber": 46
    },
    "edsNumber": 1502,
    "caseNotClosedNumber": 159,
    "deptJudgeAnalysisDtoList": [{
        "deptJudgeNumber": 1,
        "caseTotalNumber": 1,
        "orgCode": "510123",
        "percentage": 100,
        "deptId": "11C27A1584B011E885E76C",
        "name": "四川省成都市公安局温江区分局"
    }, {
        "deptJudgeNumber": 3,
        "caseTotalNumber": 4,
        "orgCode": "510105",
        "percentage": 75,
        "deptId": "11BB1DAB84B011E885E76C",
        "name": "四川省成都市公安局青羊区分局"
    }, {
        "deptJudgeNumber": 3,
        "caseTotalNumber": 4,
        "orgCode": "510106",
        "percentage": 75,
        "deptId": "11BBA20A84B011E885E76C",
        "name": "四川省成都市公安局金牛区分局"
    }, {
        "deptJudgeNumber": 1,
        "caseTotalNumber": 2,
        "orgCode": "510100S0",
        "percentage": 50,
        "deptId": "11BA2C6F84B011E885E76C",
        "name": "四川省成都市森林公安局"
    }, {
        "deptJudgeNumber": 4,
        "caseTotalNumber": 12,
        "orgCode": "51010043",
        "percentage": 33,
        "deptId": "11BA142784B011E885E76C",
        "name": "四川省成都市公安局反恐怖工作支队"
    }],
    "caseAgeAnalysisMap": {
        "18岁": 12,
        "18-35岁": 237,
        "35-50岁": 166,
        "50-70岁": 77,
        "70+岁": 1
    },
    "caseTimeWeekAnalysis": [{
        "caseNumber": 9,
        "caseTime": 0
    }, {
        "caseNumber": 5,
        "caseTime": 1
    }, {
        "caseNumber": 0,
        "caseTime": 2
    }, {
        "caseNumber": 0,
        "caseTime": 3
    }, {
        "caseNumber": 1,
        "caseTime": 4
    }, {
        "caseNumber": 0,
        "caseTime": 5
    }, {
        "caseNumber": 0,
        "caseTime": 6
    }, {
        "caseNumber": 0,
        "caseTime": 7
    }, {
        "caseNumber": 0,
        "caseTime": 8
    }, {
        "caseNumber": 0,
        "caseTime": 9
    }, {
        "caseNumber": 0,
        "caseTime": 10
    }, {
        "caseNumber": 0,
        "caseTime": 11
    }, {
        "caseNumber": 0,
        "caseTime": 12
    }, {
        "caseNumber": 0,
        "caseTime": 13
    }, {
        "caseNumber": 0,
        "caseTime": 14
    }, {
        "caseNumber": 0,
        "caseTime": 15
    }, {
        "caseNumber": 0,
        "caseTime": 16
    }, {
        "caseNumber": 0,
        "caseTime": 17
    }, {
        "caseNumber": 0,
        "caseTime": 18
    }, {
        "caseNumber": 0,
        "caseTime": 19
    }, {
        "caseNumber": 0,
        "caseTime": 20
    }, {
        "caseNumber": 0,
        "caseTime": 21
    }, {
        "caseNumber": 0,
        "caseTime": 22
    }, {
        "caseNumber": 0,
        "caseTime": 23
    }],
    "caseOccurredDayOfMonthDtoList": [{
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-08-29"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-08-30"
    }, {
        "CaseAddNotClosedNumber": 2,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 2,
        "time": "2020-08-31"
    }, {
        "CaseAddNotClosedNumber": 1,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 1,
        "time": "2020-09-01"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-02"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-03"
    }, {
        "CaseAddNotClosedNumber": 1,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 1,
        "time": "2020-09-04"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-05"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-06"
    }, {
        "CaseAddNotClosedNumber": 1,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 1,
        "time": "2020-09-07"
    }, {
        "CaseAddNotClosedNumber": 7,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 8,
        "time": "2020-09-08"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-09"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-10"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-11"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-12"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-13"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-14"
    }, {
        "CaseAddNotClosedNumber": 1,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 1,
        "time": "2020-09-15"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-16"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-17"
    }, {
        "CaseAddNotClosedNumber": 12,
        "CaseAddClosedNumber": 4,
        "CaseAddNumber": 16,
        "time": "2020-09-18"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-19"
    }, {
        "CaseAddNotClosedNumber": 3,
        "CaseAddClosedNumber": 1,
        "CaseAddNumber": 4,
        "time": "2020-09-20"
    }, {
        "CaseAddNotClosedNumber": 3,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 3,
        "time": "2020-09-21"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-22"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-23"
    }, {
        "CaseAddNotClosedNumber": 4,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 4,
        "time": "2020-09-24"
    }, {
        "CaseAddNotClosedNumber": 2,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 2,
        "time": "2020-09-25"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-26"
    }, {
        "CaseAddNotClosedNumber": 2,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 2,
        "time": "2020-09-27"
    }, {
        "CaseAddNotClosedNumber": 2,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 2,
        "time": "2020-09-28"
    }],
    "personCount": 457,
    "caseTimeYearAnalysis": [{
        "caseNumber": 21,
        "caseTime": 0
    }, {
        "caseNumber": 190,
        "caseTime": 1
    }, {
        "caseNumber": 1,
        "caseTime": 2
    }, {
        "caseNumber": 1,
        "caseTime": 3
    }, {
        "caseNumber": 1,
        "caseTime": 4
    }, {
        "caseNumber": 0,
        "caseTime": 5
    }, {
        "caseNumber": 0,
        "caseTime": 6
    }, {
        "caseNumber": 0,
        "caseTime": 7
    }, {
        "caseNumber": 0,
        "caseTime": 8
    }, {
        "caseNumber": 0,
        "caseTime": 9
    }, {
        "caseNumber": 0,
        "caseTime": 10
    }, {
        "caseNumber": 0,
        "caseTime": 11
    }, {
        "caseNumber": 0,
        "caseTime": 12
    }, {
        "caseNumber": 0,
        "caseTime": 13
    }, {
        "caseNumber": 0,
        "caseTime": 14
    }, {
        "caseNumber": 0,
        "caseTime": 15
    }, {
        "caseNumber": 0,
        "caseTime": 16
    }, {
        "caseNumber": 0,
        "caseTime": 17
    }, {
        "caseNumber": 0,
        "caseTime": 18
    }, {
        "caseNumber": 0,
        "caseTime": 19
    }, {
        "caseNumber": 0,
        "caseTime": 20
    }, {
        "caseNumber": 0,
        "caseTime": 21
    }, {
        "caseNumber": 0,
        "caseTime": 22
    }, {
        "caseNumber": 0,
        "caseTime": 23
    }],
    "caseDistrictStatisticsDtoList": [{
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 27,
        "lng": 104.10193,
        "caseDistrictId": "510108",
        "CaseNotClosedNumber": 130,
        "fullName": "成华区",
        "caseCountNumber": 157,
        "lat": 30.65993
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 104.08347,
        "caseDistrictId": "510104",
        "CaseNotClosedNumber": 2,
        "fullName": "锦江区",
        "caseCountNumber": 2,
        "lat": 30.65614
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 103.61941,
        "caseDistrictId": "510181",
        "CaseNotClosedNumber": 21,
        "fullName": "都江堰市",
        "caseCountNumber": 21,
        "lat": 30.99825
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 104.06151,
        "caseDistrictId": "510105",
        "CaseNotClosedNumber": 1,
        "fullName": "青羊区",
        "caseCountNumber": 1,
        "lat": 30.67387
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 2,
        "lng": 103.46283,
        "caseDistrictId": "510183",
        "CaseNotClosedNumber": 0,
        "fullName": "邛崃市",
        "caseCountNumber": 2,
        "lat": 30.41489
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 2,
        "lng": 104.54864,
        "caseDistrictId": "510185",
        "CaseNotClosedNumber": 0,
        "fullName": "简阳市",
        "caseCountNumber": 2,
        "lat": 30.3904
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 104.05114,
        "caseDistrictId": "510106",
        "CaseNotClosedNumber": 0,
        "fullName": "金牛区",
        "caseCountNumber": 0,
        "lat": 30.69126
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 104.04303,
        "caseDistrictId": "510107",
        "CaseNotClosedNumber": 0,
        "fullName": "武侯区",
        "caseCountNumber": 0,
        "lat": 30.64235
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 104.27462,
        "caseDistrictId": "510112",
        "CaseNotClosedNumber": 0,
        "fullName": "龙泉驿区",
        "caseCountNumber": 0,
        "lat": 30.55658
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 104.251,
        "caseDistrictId": "510113",
        "CaseNotClosedNumber": 0,
        "fullName": "青白江区",
        "caseCountNumber": 0,
        "lat": 30.87841
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 104.15921,
        "caseDistrictId": "510114",
        "CaseNotClosedNumber": 0,
        "fullName": "新都区",
        "caseCountNumber": 0,
        "lat": 30.82314
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 103.84881,
        "caseDistrictId": "510115",
        "CaseNotClosedNumber": 0,
        "fullName": "温江区",
        "caseCountNumber": 0,
        "lat": 30.68444
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 103.92373,
        "caseDistrictId": "510116",
        "CaseNotClosedNumber": 0,
        "fullName": "双流区",
        "caseCountNumber": 0,
        "lat": 30.57444
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 103.88717,
        "caseDistrictId": "510117",
        "CaseNotClosedNumber": 0,
        "fullName": "郫都区",
        "caseCountNumber": 0,
        "lat": 30.81054
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 104.41195,
        "caseDistrictId": "510121",
        "CaseNotClosedNumber": 0,
        "fullName": "金堂县",
        "caseCountNumber": 0,
        "lat": 30.86195
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 103.52075,
        "caseDistrictId": "510129",
        "CaseNotClosedNumber": 0,
        "fullName": "大邑县",
        "caseCountNumber": 0,
        "lat": 30.58738
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 103.50616,
        "caseDistrictId": "510131",
        "CaseNotClosedNumber": 0,
        "fullName": "蒲江县",
        "caseCountNumber": 0,
        "lat": 30.19667
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 103.8114,
        "caseDistrictId": "510132",
        "CaseNotClosedNumber": 0,
        "fullName": "新津县",
        "caseCountNumber": 0,
        "lat": 30.40983
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 103.958,
        "caseDistrictId": "510182",
        "CaseNotClosedNumber": 0,
        "fullName": "彭州市",
        "caseCountNumber": 0,
        "lat": 30.99011
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 103.67285,
        "caseDistrictId": "510184",
        "CaseNotClosedNumber": 0,
        "fullName": "崇州市",
        "caseCountNumber": 0,
        "lat": 30.63014
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 104.069469,
        "caseDistrictId": "510186",
        "CaseNotClosedNumber": 0,
        "fullName": "天府新区",
        "caseCountNumber": 0,
        "lat": 30.523771
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 104.067125,
        "caseDistrictId": "510187",
        "CaseNotClosedNumber": 0,
        "fullName": "高新南区",
        "caseCountNumber": 0,
        "lat": 30.595067
    }, {
        "caseCountAddNumber": 0,
        "CaseClosedNumber": 0,
        "lng": 103.930357,
        "caseDistrictId": "510188",
        "CaseNotClosedNumber": 0,
        "fullName": "高新西区",
        "caseCountNumber": 0,
        "lat": 30.766486
    }],
    "caseNumber": 191,
    "caseClosedNumber": 32,
    "caseTypeList": [{
        "showName": "黑客",
        "time": 60,
        "percent": 31
    }, {
        "showName": "盗墓",
        "time": 47,
        "percent": 24
    }, {
        "showName": "淫秽色情",
        "time": 21,
        "percent": 10
    }, {
        "showName": "赌博",
        "time": 16,
        "percent": 8
    }, {
        "showName": "制毒贩毒",
        "time": 9,
        "percent": 4
    }],
    "bankBillNumber": 32,
    "avgHandleCaseTime": 2983.8,
    "billNumber": 34,
    "caseTimeMonthAnalysis": [{
        "caseNumber": 21,
        "caseTime": 0
    }, {
        "caseNumber": 26,
        "caseTime": 1
    }, {
        "caseNumber": 1,
        "caseTime": 2
    }, {
        "caseNumber": 0,
        "caseTime": 3
    }, {
        "caseNumber": 1,
        "caseTime": 4
    }, {
        "caseNumber": 0,
        "caseTime": 5
    }, {
        "caseNumber": 0,
        "caseTime": 6
    }, {
        "caseNumber": 0,
        "caseTime": 7
    }, {
        "caseNumber": 0,
        "caseTime": 8
    }, {
        "caseNumber": 0,
        "caseTime": 9
    }, {
        "caseNumber": 0,
        "caseTime": 10
    }, {
        "caseNumber": 0,
        "caseTime": 11
    }, {
        "caseNumber": 0,
        "caseTime": 12
    }, {
        "caseNumber": 0,
        "caseTime": 13
    }, {
        "caseNumber": 0,
        "caseTime": 14
    }, {
        "caseNumber": 0,
        "caseTime": 15
    }, {
        "caseNumber": 0,
        "caseTime": 16
    }, {
        "caseNumber": 0,
        "caseTime": 17
    }, {
        "caseNumber": 0,
        "caseTime": 18
    }, {
        "caseNumber": 0,
        "caseTime": 19
    }, {
        "caseNumber": 0,
        "caseTime": 20
    }, {
        "caseNumber": 0,
        "caseTime": 21
    }, {
        "caseNumber": 0,
        "caseTime": 22
    }, {
        "caseNumber": 0,
        "caseTime": 23
    }],
    "caseOccurredDayOfWeekDtoList": [{
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-22"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-23"
    }, {
        "CaseAddNotClosedNumber": 4,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 4,
        "time": "2020-09-24"
    }, {
        "CaseAddNotClosedNumber": 2,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 2,
        "time": "2020-09-25"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-09-26"
    }, {
        "CaseAddNotClosedNumber": 2,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 2,
        "time": "2020-09-27"
    }, {
        "CaseAddNotClosedNumber": 2,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 2,
        "time": "2020-09-28"
    }],
    "caseOccurredMonthOfYearDtoList": [{
        "CaseAddNotClosedNumber": 5,
        "CaseAddClosedNumber": 7,
        "CaseAddNumber": 12,
        "time": "2019-10"
    }, {
        "CaseAddNotClosedNumber": 5,
        "CaseAddClosedNumber": 6,
        "CaseAddNumber": 11,
        "time": "2019-11"
    }, {
        "CaseAddNotClosedNumber": 39,
        "CaseAddClosedNumber": 4,
        "CaseAddNumber": 43,
        "time": "2019-12"
    }, {
        "CaseAddNotClosedNumber": 9,
        "CaseAddClosedNumber": 2,
        "CaseAddNumber": 11,
        "time": "2020-01"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-02"
    }, {
        "CaseAddNotClosedNumber": 10,
        "CaseAddClosedNumber": 1,
        "CaseAddNumber": 11,
        "time": "2020-03"
    }, {
        "CaseAddNotClosedNumber": 3,
        "CaseAddClosedNumber": 1,
        "CaseAddNumber": 4,
        "time": "2020-04"
    }, {
        "CaseAddNotClosedNumber": 0,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 0,
        "time": "2020-05"
    }, {
        "CaseAddNotClosedNumber": 19,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 19,
        "time": "2020-06"
    }, {
        "CaseAddNotClosedNumber": 5,
        "CaseAddClosedNumber": 4,
        "CaseAddNumber": 9,
        "time": "2020-07"
    }, {
        "CaseAddNotClosedNumber": 25,
        "CaseAddClosedNumber": 0,
        "CaseAddNumber": 25,
        "time": "2020-08"
    }, {
        "CaseAddNotClosedNumber": 39,
        "CaseAddClosedNumber": 5,
        "CaseAddNumber": 45,
        "time": "2020-09"
    }]
}